service: sls-opal-hello

provider:
  name: aws
  runtime: nodejs4.3
  stage: dev
  region: ap-northeast-1

package:
  exclude:
    - handler.rb
    - .git/**
    - tmp.json
    - package.json
    - .npmignore

functions:
  hello:
    handler: handler.hello
    events:
      - http:
          path: hello
          method: get

